"""Parent report safety gate — Gap 1.

Spec: SPEC_LV_REMAINING_GAPS_2026-07-29.md Gap 1 (P0).

`_strip_parent_output()` already removed AI attribution and student names
from parent drafts, but it is best-effort cleanup rather than a gate: it does
**case-sensitive exact replacement**, so a draft naming "Marco" is cleaned
while "marco" — a lowercase mention, a possessive, an inflected form — passes
straight through to the teacher's screen with no signal that anything was
missed.

`check_publication_safety()` lowercases before matching, so it catches
exactly that class of miss. Both now run: the stripper fixes what it can, the
gate reports what it could not.

Flag, never block. A draft the teacher cannot see is a draft they cannot fix,
and nothing reaches a parent until the teacher sends it themselves.
"""

from __future__ import annotations

from fastapi.testclient import TestClient

from src.web import app
import pytest

# Demo-roster seeding was removed from web.py (T9 / acceptance A6) —
# these tests exercise flows that need students on the roster, so they
# opt in to the explicit demo_roster fixture from conftest.py.
pytestmark = pytest.mark.usefixtures("demo_roster")


client = TestClient(app)


def _draft(**payload):
    response = client.post("/api/parents/recommendation", json=payload)
    assert response.status_code == 200, response.status_code
    return response.json()


def _student_named(fragment: str) -> str | None:
    for student in client.get("/api/students").json()["students"]:
        if fragment.lower() in (student.get("display_name") or "").lower():
            return student["student_id"]
    return None


# --- the gate is wired at all ----------------------------------------------


def test_every_draft_reports_its_publication_safety():
    draft = _draft(student_id="student-marco")
    assert "publication_safety" in draft
    assert "blocked" in draft["publication_safety"]


def test_a_clean_draft_is_not_flagged():
    draft = _draft(student_id="student-marco")
    assert draft["publication_safety"]["blocked"] is False
    assert draft.get("review_required") is None
    assert draft.get("safety_warnings") is None


# --- the miss the gate exists to catch --------------------------------------


def test_a_name_the_stripper_misses_is_flagged():
    """The core case. _strip_parent_output() replaces "Marco" exactly, so a
    lowercase "marco" survives it — and previously reached the teacher with
    no warning at all."""
    student_id = _student_named("marco")
    assert student_id, "demo roster should seed a student named Marco"

    draft = _draft(student_id=student_id, focus="game marco enjoys at home")

    assert draft["review_required"] is True
    rules = [violation["rule"] for violation in draft["safety_warnings"]]
    assert "privacy_rules.student_data" in rules


def test_the_flagged_draft_is_still_returned():
    """Flag, don't block: the teacher has to see it to fix it."""
    student_id = _student_named("marco")
    draft = _draft(student_id=student_id, focus="game marco enjoys at home")

    assert draft["body"], "a flagged draft must still be shown"
    assert draft["subject_line"]
    assert "marco" in draft["body"].lower(), (
        "the offending text must remain visible so the teacher can correct it"
    )


def test_the_warning_names_the_problem_without_prescribing_the_wrong_fix():
    """This gate runs on observation exports too, which need a different
    remedy, so the message states the fact and the UI supplies the fix."""
    student_id = _student_named("marco")
    draft = _draft(student_id=student_id, focus="game marco enjoys at home")

    message = draft["safety_warnings"][0]["message"]
    assert "name appears" in message
    assert "export" not in message.lower(), "export wording on a parent draft"


# --- defence in depth is still in place -------------------------------------


def test_the_stripper_still_runs():
    """The gate reports; it does not replace the cleanup. An exactly-matching
    name must still be removed, not merely flagged."""
    student_id = _student_named("marco")
    draft = _draft(student_id=student_id)

    assert "Marco" not in draft["body"], "exact-case name should still be stripped"
    assert "your child" in draft["body"].lower()


def test_ai_attribution_is_still_stripped_and_would_be_caught():
    draft = _draft(student_id="student-marco")
    lowered = draft["body"].lower()
    for phrase in ("as an ai", "language model", "generated by ai"):
        assert phrase not in lowered


# --- the UI actually renders it ---------------------------------------------


def test_ui_renders_warnings_above_the_draft_not_as_a_toast():
    body = client.get("/").text
    assert "data.safety_warnings" in body, "UI never reads the warnings"
    assert "Check this before sending" in body
    # Prominent, per the spec: a bordered block, and placed before the draft.
    assert "border:2px solid var(--risk)" in body
    assert body.index("${warnings}") < body.index("<textarea>")
