"""
Drive Sync — automatic lens-to-Drive push after any lens mutation.

When a sync folder is configured, any lens update (observation save, extraction
write, manual edit) triggers an async push of the updated lens file to Drive.

Sync is fire-and-forget: failures are logged but never block the save.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src.lingua_viva.config import lv_home

logger = logging.getLogger(__name__)

SYNC_CONFIG_KEY = "drive_sync_folder_id"
PENDING_SYNCS_FILE = "pending_drive_syncs.json"


def get_sync_folder_id() -> Optional[str]:
    """Read the configured sync folder ID from config."""
    config_path = lv_home() / "config" / "settings.json"
    if not config_path.exists():
        return None
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
        folder_id = data.get(SYNC_CONFIG_KEY)
        return str(folder_id).strip() if folder_id else None
    except (json.JSONDecodeError, OSError):
        return None


def set_sync_folder_id(folder_id: str) -> None:
    """Write the sync folder ID to config."""
    config_dir = lv_home() / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "settings.json"
    data = {}
    if config_path.exists():
        try:
            data = json.loads(config_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    data[SYNC_CONFIG_KEY] = folder_id.strip()
    config_path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def format_lens_markdown(student_data: dict) -> str:
    """Format a student lens as a readable Markdown file for Drive export."""
    name = student_data.get("display_name", "Unknown Student")
    grade = student_data.get("grade_level", "")
    student_id = student_data.get("student_id", "")
    trajectory = student_data.get("cefr_trajectory", "unknown")
    support_tier = student_data.get("support_tier", "")
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# Student Lens: {name}",
        "",
        f"**Student ID**: {student_id}",
        f"**Grade**: {grade}" if grade else "",
        f"**CEFR trajectory**: {trajectory}",
        f"**Support tier**: {support_tier}" if support_tier else "",
        f"**Last updated**: {updated}",
        "",
    ]

    # Support profile
    support = student_data.get("support_profile", {})
    if support:
        lines.append("## Support Profile")
        lines.append("")
        categories = support.get("categories", {})
        for cat_id, cat_data in categories.items():
            if isinstance(cat_data, dict):
                label = cat_data.get("label", cat_id)
                lines.append(f"### {label}")
                strengths = cat_data.get("strengths", [])
                if strengths:
                    for s in strengths:
                        lines.append(f"- ✓ {s}")
                needs = cat_data.get("needs", [])
                if needs:
                    for n in needs:
                        lines.append(f"- ⚠ {n}")
                strategies = cat_data.get("strategies", [])
                if strategies:
                    for st in strategies:
                        lines.append(f"- → {st}")
                lines.append("")

    # Recent observations
    observations = student_data.get("observations", student_data.get("recent_observations", []))
    if observations:
        lines.append("## Recent Observations")
        lines.append("")
        for obs in observations[:10]:
            date = obs.get("created_at", "")[:10] if obs.get("created_at") else ""
            text = obs.get("raw_transcript", obs.get("text", ""))
            level = obs.get("observed_level", "")
            lines.append(f"- [{date}] {text}" + (f" (CEFR {level})" if level else ""))
        lines.append("")

    # Grouping notes
    grouping = student_data.get("grouping", {})
    if grouping:
        avoid = grouping.get("avoid_pairing_notes", "")
        if avoid:
            lines.append(f"## Grouping Notes")
            lines.append(f"Avoid-pairing: {avoid}")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Lingua Viva · {updated}*")
    return "\n".join(line for line in lines if line is not None)


def _safe_filename(name: str) -> str:
    """Create a Drive-safe filename from a student name."""
    safe = "".join(c if c.isalnum() or c in " -_" else "_" for c in name)
    return safe.strip()[:50] or "student"


async def sync_lens_to_drive(student_id: str) -> bool:
    """Push a student lens to the configured Drive sync folder.

    Returns True if sync succeeded, False if it failed or was skipped.
    This function is designed to be called via asyncio.create_task() —
    it never raises.
    """
    try:
        folder_id = get_sync_folder_id()
        if not folder_id:
            return False

        # Load the student lens (full export includes observations)
        from src.education.student_lens import StudentLensStore

        store = StudentLensStore()
        try:
            lens_data = store.export_lens(student_id)
            if not lens_data:
                return False
        finally:
            store.close()

        # Format as markdown
        content = format_lens_markdown(lens_data)
        display_name = lens_data.get("display_name", student_id)
        filename = f"{_safe_filename(display_name)}_lens.md"

        # Upload to Drive
        from src.lingua_viva.google_drive_integration import (
            upload_text_to_folder,
        )

        await asyncio.to_thread(
            upload_text_to_folder,
            folder_id=folder_id,
            filename=filename,
            content=content,
            mime_type="text/markdown",
        )
        logger.info(f"Synced lens for {student_id} to Drive folder {folder_id}")
        return True

    except Exception as exc:
        logger.warning(f"Drive sync failed for {student_id}: {exc}")
        _record_pending_sync(student_id)
        return False


def _record_pending_sync(student_id: str) -> None:
    """Record a failed sync so it can be retried later."""
    pending_path = lv_home() / PENDING_SYNCS_FILE
    pending: list = []
    if pending_path.exists():
        try:
            pending = json.loads(pending_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    # Add if not already pending
    if student_id not in pending:
        pending.append(student_id)
        # Keep bounded
        pending = pending[-50:]
    try:
        pending_path.write_text(json.dumps(pending), encoding="utf-8")
    except OSError:
        pass


async def retry_pending_syncs() -> int:
    """Retry any pending syncs. Returns count of successful retries."""
    pending_path = lv_home() / PENDING_SYNCS_FILE
    if not pending_path.exists():
        return 0
    try:
        pending = json.loads(pending_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return 0
    if not pending:
        return 0

    succeeded = []
    for student_id in list(pending):
        if await sync_lens_to_drive(student_id):
            succeeded.append(student_id)

    # Remove succeeded from pending
    remaining = [s for s in pending if s not in succeeded]
    try:
        pending_path.write_text(json.dumps(remaining), encoding="utf-8")
    except OSError:
        pass
    return len(succeeded)


def trigger_sync(student_id: str) -> None:
    """Fire-and-forget sync trigger. Safe to call from any context."""
    try:
        loop = asyncio.get_running_loop()
        loop.create_task(sync_lens_to_drive(student_id))
    except RuntimeError:
        # No running loop — skip sync (happens in test/CLI contexts)
        pass
