"""Gauntlet phase 4 — parent reports grounded in real observation history.

Marco Bianchi is seeded (conftest) with two progressing CEFR speaking
observations (A1 → A2) and one sel_positive — the exact history the
generator's strengths logic keys on. Oscar Sanna has zero observations —
his report must be honestly empty, never invented.
"""

from __future__ import annotations

import pytest

from src.education.content_differentiator import TraumaSafetyError
from src.education.parent_report import (
    ParentReportGenerator,
    render_parent_report_html,
)

from .conftest import EXPECTED_STUDENTS


def _draft(gauntlet_env, name: str, **kwargs):
    generator = ParentReportGenerator(gauntlet_env["store"])
    return generator.generate_draft(
        gauntlet_env["student_ids"][name], gauntlet_env["teacher_id"], **kwargs
    )


# --- observation-grounded content --------------------------------------------


def test_observed_student_report_reflects_the_cefr_improvement(gauntlet_env):
    draft = _draft(gauntlet_env, "Marco Bianchi")
    assert draft.strengths, "improved speaking + sel positive must yield strengths"
    assert any("speaking" in s for s in draft.strengths)
    assert "Marco Bianchi" in draft.subject_line


def test_observed_student_report_reflects_the_sel_positive(gauntlet_env):
    draft = _draft(gauntlet_env, "Marco Bianchi")
    assert any("care and attention" in s for s in draft.strengths)


def test_home_activity_matches_the_observed_dimension(gauntlet_env):
    """Marco's history is speaking — the suggested home activity must be the
    speaking one, not a generic filler."""
    draft = _draft(gauntlet_env, "Marco Bianchi")
    assert any("tell you about one thing from their day" in a for a in draft.home_activities)


def test_report_never_surfaces_clinical_or_tier_language(gauntlet_env):
    draft = _draft(gauntlet_env, "Marco Bianchi")
    blob = " ".join([draft.subject_line, draft.body, *draft.home_activities]).lower()
    for banned in ("tier", "rti", "intervention", "diagnosis", "concern logged"):
        assert banned not in blob, banned


# --- honest empties -----------------------------------------------------------


def test_unobserved_student_report_is_honestly_empty(gauntlet_env):
    draft = _draft(gauntlet_env, "Oscar Sanna")
    assert "still collecting classroom observations" in draft.body
    assert draft.strengths == []
    assert draft.growth_areas == []
    # even an empty report offers the parent something real to do
    assert draft.home_activities


def test_unobserved_student_report_fabricates_no_progress_claims(gauntlet_env):
    draft = _draft(gauntlet_env, "Oscar Sanna")
    for phrase in ("progress is visible", "growing confidence", "care and attention"):
        assert phrase not in draft.body


# --- rendering ----------------------------------------------------------------


def test_rendered_report_with_blank_name_shows_fill_in_line(gauntlet_env, monkeypatch, tmp_path):
    """The name-stripped draft surface (web.py) runs every field through
    _strip_parent_output before rendering — the printable carries a fill-in
    line the teacher completes by hand, never the student's name."""
    monkeypatch.setenv("LV_PRIVACY_LOG_PATH", str(tmp_path / "privacy.ndjson"))
    from src.web import _strip_parent_output

    draft = _draft(gauntlet_env, "Marco Bianchi")
    names = list(EXPECTED_STUDENTS)
    html = render_parent_report_html(
        {
            "student_name": "",
            "strengths": [_strip_parent_output(s, names) for s in draft.strengths],
            "growth_areas": [_strip_parent_output(g, names) for g in draft.growth_areas],
            "home_activities": [_strip_parent_output(a, names) for a in draft.home_activities],
            "intro": _strip_parent_output(draft.intro, names),
        }
    )
    assert "fill-line" in html
    assert "Marco Bianchi" not in html
    assert "your child" in html


def test_rendered_report_shows_honest_empty_notes_not_invented_bullets(gauntlet_env):
    html = render_parent_report_html(
        {"student_name": "", "strengths": [], "growth_areas": [], "home_activities": []}
    )
    assert "We are still collecting classroom observations for this section." in html
    assert html.count("None noted for this period.") == 2


def test_rendered_report_has_signature_line_and_no_ai_attribution(gauntlet_env):
    draft = _draft(gauntlet_env, "Marco Bianchi")
    html = render_parent_report_html(
        {"student_name": "", "strengths": draft.strengths, "home_activities": draft.home_activities}
    )
    assert "signature" in html
    for marker in ("AI", "generated by", "model", "Claude"):
        assert marker not in html, marker


def test_rendered_report_escapes_html_in_content(gauntlet_env):
    html = render_parent_report_html(
        {"student_name": "", "strengths": ["<script>alert(1)</script>"], "home_activities": []}
    )
    assert "<script>" not in html
    assert "&lt;script&gt;" in html


# --- safety gate --------------------------------------------------------------


def test_teacher_edit_reintroducing_labeling_phrase_is_blocked(gauntlet_env):
    """approve() re-checks trauma safety — an edit can't reintroduce a label
    the generator would never produce."""
    generator = ParentReportGenerator(gauntlet_env["store"])
    draft = _draft(gauntlet_env, "Marco Bianchi")
    with pytest.raises(TraumaSafetyError):
        generator.approve(
            draft,
            "Ms. Rossi",
            teacher_edited_body="As a trauma survivor, Marco has come far this term.",
        )


def test_approved_artifact_hard_locks_attribution_off(gauntlet_env):
    generator = ParentReportGenerator(gauntlet_env["store"])
    draft = _draft(gauntlet_env, "Marco Bianchi")
    artifact = generator.approve(draft, "Ms. Rossi")
    assert artifact.attribution_visible_to_parent is False
    assert artifact.from_label == "Ms. Rossi (Class Teacher)"


def test_no_other_students_name_appears_in_marcos_report(gauntlet_env):
    """A report about one student may name that student to their own parent —
    but never any classmate."""
    draft = _draft(gauntlet_env, "Marco Bianchi")
    blob = " ".join([draft.subject_line, draft.body, *draft.strengths, *draft.home_activities])
    for name in EXPECTED_STUDENTS:
        if name == "Marco Bianchi":
            continue
        assert name not in blob, name
