from __future__ import annotations

import hashlib
import json
import os
import re
import uuid
from collections import Counter
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.education.content_differentiator import (
    TIERS,
    ContentDifferentiator,
    LessonInput,
    _check_trauma_safety,
)
from src.education.teacher_guide import TeacherGuideGenerator
from src.education.trend_analysis import TrendAnalyzer

VALID_STATUSES = ("draft", "approved", "rejected")
UNSAFE_PLAN_MARKERS = (
    "diagnosis",
    "diagnostic",
    "disorder",
    "refugee",
    "trauma survivor",
    "traumatized",
    "generated by ai",
    "ai-generated",
    "written by ai",
    "the ai",
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _state_root() -> Path:
    env = os.environ.get("LV_STATE_HOME", "").strip()
    if env:
        return Path(env).expanduser()
    from src.lingua_viva.config import lv_home

    return lv_home() / "runtime"


def records_path() -> Path:
    path = _state_root() / "cohort_plans" / "records.ndjson"
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def _compact(value: object, limit: int = 800) -> str:
    return " ".join(str(value or "").split())[:limit].rstrip()


def _json_text(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)


def _support_flags(lens: dict) -> list[str]:
    flags: list[str] = []
    categories = ((lens.get("support_profile") or {}).get("categories") or {})
    for category_id, category in sorted(categories.items()):
        if not isinstance(category, dict):
            continue
        if any(category.get(bucket) for bucket in ("needs", "strategies_worked", "strategies_not_worked", "evidence", "open_questions")):
            flags.append(str(category_id))
    return flags


def _valid_cefr_values(lens: dict) -> list[str]:
    snapshot = lens.get("cefr_snapshot") or {}
    return [str(level) for level in snapshot.values() if level]


def _manual_review_reasons(store, lens: dict, observations: list[dict], unplaced: set[str]) -> list[str]:
    reasons: list[str] = []
    student_id = str(lens.get("student_id") or "")
    if not _valid_cefr_values(lens):
        reasons.append("missing_cefr")
    if not observations:
        reasons.append("missing_observations")
    if store.evaluate_rti_rules(student_id):
        reasons.append("active_rti_escalation")
    if student_id in unplaced:
        reasons.append("grouping_review")
    return reasons


def _summary_from_roster(store, roster: list[dict], assignments: dict[str, str], unplaced: set[str]) -> "CohortPlanningSummary":
    cefr_counts: Counter[str] = Counter()
    support_counts: Counter[str] = Counter()
    manual_ids: list[str] = []
    flagged_count = 0
    for lens in roster:
        student_id = str(lens.get("student_id") or "")
        for level in _valid_cefr_values(lens):
            cefr_counts[level] += 1
        flags = _support_flags(lens)
        for flag in flags:
            support_counts[flag] += 1
        observations = store.export_lens(student_id).get("observations") or [] if student_id else []
        reasons = _manual_review_reasons(store, lens, observations, unplaced)
        if reasons:
            manual_ids.append(student_id)
        if store.evaluate_rti_rules(student_id):
            flagged_count += 1
    return CohortPlanningSummary(
        total_students=len(roster),
        tier_counts={tier: sum(1 for value in assignments.values() if value == tier) for tier in TIERS},
        cefr_distribution=dict(sorted(cefr_counts.items())),
        support_focus_counts=dict(sorted(support_counts.items())),
        flagged_student_count=flagged_count,
        manual_review_student_ids=manual_ids,
    )


def _student_facing_pack_text(content_pack: dict) -> str:
    return _json_text((content_pack.get("tiers") or {}))


def validate_plan_safety(record: "CohortLessonPlanRecord") -> None:
    text = _json_text(record.as_dict())
    lowered = text.lower()
    for marker in UNSAFE_PLAN_MARKERS:
        if marker in lowered:
            raise ValueError(f"unsafe_teacher_edit:{marker}")
    _check_trauma_safety(text)

    student_facing = _student_facing_pack_text(record.content_pack).lower()
    for assignment in record.student_assignments:
        name = assignment.display_name.strip()
        if len(name) >= 3 and name.lower() in student_facing:
            raise ValueError("student_name_in_tier_content")


@dataclass
class CohortStudentAssignment:
    student_id: str
    display_name: str
    assigned_tier: str
    rti_tier: int
    cefr_snapshot: dict
    support_flags: list[str]
    grouping_notes: list[str]

    def as_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "CohortStudentAssignment":
        known = {key: value for key, value in dict(data).items() if key in cls.__dataclass_fields__}
        return cls(**known)


@dataclass
class CohortPlanningSummary:
    total_students: int
    tier_counts: dict
    cefr_distribution: dict
    support_focus_counts: dict
    flagged_student_count: int
    manual_review_student_ids: list[str]

    def as_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "CohortPlanningSummary":
        return cls(
            total_students=int(data.get("total_students") or 0),
            tier_counts=dict(data.get("tier_counts") or {}),
            cefr_distribution=dict(data.get("cefr_distribution") or {}),
            support_focus_counts=dict(data.get("support_focus_counts") or {}),
            flagged_student_count=int(data.get("flagged_student_count") or 0),
            manual_review_student_ids=list(data.get("manual_review_student_ids") or []),
        )


@dataclass
class CohortLessonPlanRecord:
    plan_id: str
    teacher_id: str
    created_at: str
    status: str
    lesson: dict
    cohort_summary: CohortPlanningSummary
    student_assignments: list[CohortStudentAssignment]
    content_pack: dict
    teacher_guide_markdown: str
    source_mode: str
    source_provenance: list[dict]
    teacher_notes: list[str] = field(default_factory=list)
    safety_notes: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.status not in VALID_STATUSES:
            self.status = "draft"

    def as_dict(self) -> dict:
        data = asdict(self)
        data["cohort_summary"] = self.cohort_summary.as_dict()
        data["student_assignments"] = [item.as_dict() for item in self.student_assignments]
        return data

    @classmethod
    def from_dict(cls, data: dict) -> "CohortLessonPlanRecord":
        payload = dict(data)
        summary = payload.get("cohort_summary") or {}
        assignments = payload.get("student_assignments") or []
        return cls(
            plan_id=str(payload.get("plan_id") or f"COHORT-{uuid.uuid4().hex[:12]}"),
            teacher_id=str(payload.get("teacher_id") or ""),
            created_at=str(payload.get("created_at") or _now_iso()),
            status=str(payload.get("status") or "draft"),
            lesson=dict(payload.get("lesson") or {}),
            cohort_summary=summary if isinstance(summary, CohortPlanningSummary) else CohortPlanningSummary.from_dict(summary),
            student_assignments=[
                item if isinstance(item, CohortStudentAssignment) else CohortStudentAssignment.from_dict(item)
                for item in assignments
                if isinstance(item, (dict, CohortStudentAssignment))
            ],
            content_pack=dict(payload.get("content_pack") or {}),
            teacher_guide_markdown=str(payload.get("teacher_guide_markdown") or ""),
            source_mode=str(payload.get("source_mode") or "generated"),
            source_provenance=list(payload.get("source_provenance") or []),
            teacher_notes=[_compact(item, 1000) for item in payload.get("teacher_notes") or [] if str(item).strip()],
            safety_notes=[_compact(item, 1000) for item in payload.get("safety_notes") or [] if str(item).strip()],
        )


def generate_cohort_plan(
    store,
    teacher_id: str,
    lesson: LessonInput,
    student_ids: list[str] | None = None,
    teacher_notes: list[str] | None = None,
    retriever=None,
) -> CohortLessonPlanRecord:
    roster = store.list_lenses_for_teacher(teacher_id)
    roster_by_id = {str(lens.get("student_id")): lens for lens in roster}
    if student_ids:
        requested = [str(sid) for sid in student_ids if str(sid).strip()]
        unknown = sorted(sid for sid in requested if sid not in roster_by_id)
        if unknown:
            raise PermissionError(f"unauthorized_student_ids:{','.join(unknown)}")
        roster = [roster_by_id[sid] for sid in requested]

    diff = ContentDifferentiator()
    pack = (
        diff.generate_from_documents(lesson, retriever, domain="curriculum")
        if retriever is not None
        else diff.generate(lesson)
    )
    assignments = {str(lens.get("student_id")): diff.assign_tier_for_student(lens) for lens in roster}
    guide = TeacherGuideGenerator().generate(pack, roster, assignments)
    unplaced = set(guide.unplaced_for_grouping)

    student_assignments: list[CohortStudentAssignment] = []
    for lens in roster:
        student_id = str(lens.get("student_id") or "")
        observations = store.export_lens(student_id).get("observations") or [] if student_id else []
        review_reasons = _manual_review_reasons(store, lens, observations, unplaced)
        student_assignments.append(
            CohortStudentAssignment(
                student_id=student_id,
                display_name=str(lens.get("display_name") or ""),
                assigned_tier=assignments.get(student_id, "foundational"),
                rti_tier=int(lens.get("rti_current_tier") or 1),
                cefr_snapshot=dict(lens.get("cefr_snapshot") or {}),
                support_flags=_support_flags(lens),
                grouping_notes=review_reasons,
            )
        )

    class_summary = TrendAnalyzer(store).analyze_class(teacher_id)
    guide_markdown = guide.to_markdown()
    if roster:
        guide_markdown += "\n## Planning Workflow\n\n"
        guide_markdown += "- Before class: prepare tier packets and place visual supports for foundational tasks.\n"
        guide_markdown += "- During class: circulate first to manual-review students, then check each tier once.\n"
        guide_markdown += "- After class: record one short observation for any student listed for manual review.\n"
        guide_markdown += f"- Class context: {class_summary.student_count} roster student(s), {class_summary.students_flagged} active flag(s).\n"
    else:
        guide_markdown += "\n## Planning Workflow\n\n- No teacher-owned roster lenses were found for this lesson plan.\n"

    record = CohortLessonPlanRecord(
        plan_id=f"COHORT-{uuid.uuid4().hex[:12]}",
        teacher_id=teacher_id,
        created_at=_now_iso(),
        status="draft",
        lesson=asdict(lesson),
        cohort_summary=_summary_from_roster(store, roster, assignments, unplaced),
        student_assignments=student_assignments,
        content_pack=pack.to_dict(),
        teacher_guide_markdown=guide_markdown,
        source_mode=pack.source_mode,
        source_provenance=list(pack.source_provenance or []),
        teacher_notes=[_compact(item, 1000) for item in teacher_notes or [] if str(item).strip()],
        safety_notes=[
            "Draft only. Teacher approval required.",
            "No raw observation transcript is included.",
            "No student lenses or RTI tiers were changed.",
            "Local planning deliverable only; not sent or shared.",
        ],
    )
    validate_plan_safety(record)
    return record


def _apply_teacher_edits(record: CohortLessonPlanRecord, teacher_edits: dict[str, Any] | None) -> CohortLessonPlanRecord:
    edits = teacher_edits or {}
    data = record.as_dict()
    if isinstance(edits.get("teacher_notes"), list):
        data["teacher_notes"] = [_compact(item, 1000) for item in edits["teacher_notes"] if str(item).strip()]
    if isinstance(edits.get("teacher_guide_markdown"), str) and edits["teacher_guide_markdown"].strip():
        data["teacher_guide_markdown"] = _compact(edits["teacher_guide_markdown"], 12000)
    data["status"] = "approved"
    approved = CohortLessonPlanRecord.from_dict(data)
    validate_plan_safety(approved)
    return approved


def approve_cohort_plan(record_or_payload: CohortLessonPlanRecord | dict, teacher_edits: dict[str, Any] | None = None) -> CohortLessonPlanRecord:
    record = record_or_payload if isinstance(record_or_payload, CohortLessonPlanRecord) else CohortLessonPlanRecord.from_dict(record_or_payload)
    return _apply_teacher_edits(record, teacher_edits)


def save_cohort_plan(record: CohortLessonPlanRecord) -> dict:
    payload = record.as_dict()
    path = records_path()
    existing = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    existing.append(json.dumps(payload, ensure_ascii=True, sort_keys=True))
    tmp = path.with_name(f".{path.name}.tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            for line in existing:
                handle.write(line + "\n")
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise
    os.chmod(path, 0o600)
    return payload


def read_cohort_plans(teacher_id: str = "", limit: int = 50) -> list[dict]:
    path = records_path()
    if not path.exists():
        return []
    rows: list[CohortLessonPlanRecord] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.strip():
            continue
        try:
            record = CohortLessonPlanRecord.from_dict(json.loads(line))
        except (json.JSONDecodeError, TypeError, ValueError):
            continue
        if teacher_id and record.teacher_id != teacher_id:
            continue
        rows.append(record)
    rows.sort(key=lambda item: item.created_at, reverse=True)
    return [record.as_dict() for record in rows[: max(0, int(limit))]]


def content_hash(record: CohortLessonPlanRecord | dict) -> str:
    data = record if isinstance(record, dict) else record.as_dict()
    return hashlib.sha256(_json_text(data).encode("utf-8")).hexdigest()[:20]
