from __future__ import annotations

import hashlib
import json
import os
import re
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.education.content_differentiator import ContentDifferentiator, _check_trauma_safety
from src.education.student_lens import StudentLensStore


VALID_ARTIFACT_TYPES = ("practice", "scaffold", "check_in", "review")
VALID_STATUSES = ("draft", "approved", "rejected")
UNSAFE_STUDENT_COPY = (
    "rti",
    "tier 2",
    "tier 3",
    "diagnosis",
    "diagnostic",
    "disorder",
    "refugee",
    "trauma survivor",
    "traumatized",
    "generated by ai",
    "ai-generated",
    "written by ai",
    "the ai",
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _state_root() -> Path:
    env = os.environ.get("LV_STATE_HOME", "").strip()
    if env:
        return Path(env).expanduser()
    from src.lingua_viva.config import lv_home

    return lv_home() / "runtime"


def records_path() -> Path:
    path = _state_root() / "teacher_decisions" / "records.ndjson"
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def _compact(text: str, limit: int = 220) -> str:
    text = " ".join(str(text or "").split())
    return text[:limit].rstrip()


def _hash_payload(*parts: str) -> str:
    return hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()[:20]


def _latest_observations(lens: dict, limit: int = 5) -> list[dict]:
    observations = list(lens.get("observations") or [])
    observations.sort(key=lambda item: str(item.get("recorded_at") or ""), reverse=True)
    return observations[:limit]


def _source_ids(observations: list[dict]) -> list[str]:
    return [str(obs.get("observation_id") or "") for obs in observations if obs.get("observation_id")]


def _weakest_cefr(lens: dict) -> tuple[str, str]:
    from src.education.content_differentiator import CEFR_ORDER

    snapshot = lens.get("cefr_snapshot") or {}
    candidates = [
        (dimension, level)
        for dimension, level in snapshot.items()
        if level in CEFR_ORDER and dimension in {"reading", "writing", "speaking", "listening"}
    ]
    if not candidates:
        return "speaking", "A1"
    return min(candidates, key=lambda item: CEFR_ORDER.index(item[1]))


def _support_focus(lens: dict) -> tuple[str, str]:
    support = lens.get("support_profile") or {}
    categories = support.get("categories") or {}
    for category_id, category in categories.items():
        evidence = category.get("evidence") or []
        if evidence:
            return str(category_id), _compact(evidence[-1].get("summary") or category_id, 120)
    return "", ""


def _source_summary(lens: dict, observations: list[dict]) -> str:
    domain, level = _weakest_cefr(lens)
    support_id, support_summary = _support_focus(lens)
    pieces = [f"Recent evidence points to {domain} at about {level}."]
    if support_summary:
        pieces.append(f"Support evidence: {support_summary}.")
    if observations:
        pieces.append(f"{len(observations)} recent observation(s) were reviewed.")
    return " ".join(pieces)


def _safe_skill_phrase(domain: str) -> str:
    phrases = {
        "reading": "finding the main idea",
        "writing": "building a clear sentence",
        "speaking": "sharing an idea aloud",
        "listening": "noticing key words while listening",
    }
    return phrases.get(domain, "using the target skill")


def _artifact_copy(tier: str, domain: str, artifact_type: str) -> tuple[str, str, str, list[str]]:
    skill = _safe_skill_phrase(domain)
    if tier == "foundational":
        instructions = (
            "Work in three short steps: look at the example, try one guided item, "
            "then choose one word or sentence you feel ready to share."
        )
        prompt = f"Use the frame to practise {skill}: I notice __ because __."
        notes = ["Offer a model first.", "Let the student point, draw, or say the answer."]
    elif tier == "extended":
        instructions = (
            "Start independently, then add one extra reason or example that shows "
            "how the idea connects to a new text or situation."
        )
        prompt = f"Show {skill}, then add a second example or challenge question."
        notes = ["Invite transfer to a new context.", "Ask for evidence, not speed."]
    else:
        instructions = (
            "Read the short prompt, try independently, then check your answer "
            "with one partner or with the teacher."
        )
        prompt = f"Practise {skill} and explain one choice you made."
        notes = ["Keep one scaffold visible.", "Praise the strategy the student used."]
    if artifact_type == "check_in":
        prompt = f"Quick check: {prompt}"
    elif artifact_type == "review":
        instructions = f"Review a familiar example first. {instructions}"
    elif artifact_type == "scaffold":
        notes.append("Keep the scaffold available, then remove one support when ready.")
    return instructions, prompt, prompt, notes


def _validate_safe_text(*values: str) -> None:
    joined = "\n".join(values)
    lowered = joined.lower()
    for marker in UNSAFE_STUDENT_COPY:
        if marker in lowered:
            raise ValueError(f"unsafe_student_facing_copy:{marker}")
    _check_trauma_safety(joined)


@dataclass
class HelpArtifactRecord:
    artifact_id: str
    student_id: str
    teacher_id: str
    created_at: str
    status: str
    artifact_type: str
    source_observation_ids: list[str]
    source_summary: str
    target_domain: str
    cefr_level: str
    rti_tier: int
    differentiation_tier: str
    title: str
    instructions: str
    student_prompt: str
    teacher_notes: list[str]
    safety_notes: list[str]

    def __post_init__(self) -> None:
        if self.status not in VALID_STATUSES:
            self.status = "draft"
        if self.artifact_type not in VALID_ARTIFACT_TYPES:
            self.artifact_type = "practice"

    def as_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "HelpArtifactRecord":
        known = {key: value for key, value in dict(data).items() if key in cls.__dataclass_fields__}
        return cls(**known)


@dataclass
class PortfolioEntryRecord:
    portfolio_entry_id: str
    student_id: str
    teacher_id: str
    created_at: str
    status: str
    source_observation_ids: list[str]
    title: str
    body: str
    evidence_tags: list[str]
    safety_notes: list[str]

    def __post_init__(self) -> None:
        if self.status not in VALID_STATUSES:
            self.status = "draft"

    def as_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "PortfolioEntryRecord":
        known = {key: value for key, value in dict(data).items() if key in cls.__dataclass_fields__}
        return cls(**known)


def _record_kind(data: dict) -> str:
    if "artifact_id" in data:
        return "help_artifact"
    if "portfolio_entry_id" in data:
        return "portfolio_entry"
    return ""


def save_draft(record: HelpArtifactRecord | PortfolioEntryRecord) -> dict:
    payload = record.as_dict()
    payload["_kind"] = _record_kind(payload)
    path = records_path()
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(payload, ensure_ascii=True, sort_keys=True) + "\n")
    os.chmod(path, 0o600)
    return record.as_dict()


def read_records() -> list[dict]:
    path = records_path()
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []
    rows: list[dict] = []
    for line in lines:
        if not line.strip():
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return rows


def generate_help_artifact(
    store: StudentLensStore,
    student_id: str,
    teacher_id: str,
    artifact_type: str = "practice",
) -> HelpArtifactRecord:
    lens = store.export_lens(student_id)
    observations = _latest_observations(lens)
    domain, cefr_level = _weakest_cefr(lens)
    support_id, _support_summary = _support_focus(lens)
    target_domain = support_id or domain
    differentiation_tier = ContentDifferentiator().assign_tier_for_student(lens)
    instructions, student_prompt, _summary_prompt, notes = _artifact_copy(
        differentiation_tier, domain, artifact_type
    )
    title = f"{_safe_skill_phrase(domain).title()} Practice"
    source_summary = _source_summary(lens, observations)
    record = HelpArtifactRecord(
        artifact_id=f"HLP-{uuid.uuid4().hex[:12]}",
        student_id=student_id,
        teacher_id=teacher_id,
        created_at=_now_iso(),
        status="draft",
        artifact_type=artifact_type if artifact_type in VALID_ARTIFACT_TYPES else "practice",
        source_observation_ids=_source_ids(observations),
        source_summary=source_summary,
        target_domain=target_domain,
        cefr_level=cefr_level,
        rti_tier=int(lens.get("rti_current_tier") or 1),
        differentiation_tier=differentiation_tier,
        title=title,
        instructions=instructions,
        student_prompt=student_prompt,
        teacher_notes=notes,
        safety_notes=[
            "Draft only. Teacher approval required.",
            "No raw observation transcript is included.",
            "Do not send or share until reviewed.",
        ],
    )
    _validate_safe_text(record.instructions, record.student_prompt, record.title)
    return record


def generate_portfolio_entry(
    store: StudentLensStore,
    student_id: str,
    teacher_id: str,
) -> PortfolioEntryRecord:
    lens = store.export_lens(student_id)
    observations = _latest_observations(lens, limit=3)
    domain, _level = _weakest_cefr(lens)
    skill = _safe_skill_phrase(domain)
    evidence_tags = [domain]
    support_id, _support_summary = _support_focus(lens)
    if support_id:
        evidence_tags.append(support_id)
    body = (
        f"This learning story notices growth in {skill}. The next step is to "
        "keep practising with a clear model, a short try, and a chance to explain one choice."
    )
    record = PortfolioEntryRecord(
        portfolio_entry_id=f"PF-{uuid.uuid4().hex[:12]}",
        student_id=student_id,
        teacher_id=teacher_id,
        created_at=_now_iso(),
        status="draft",
        source_observation_ids=_source_ids(observations),
        title=f"Learning story: {skill}",
        body=body,
        evidence_tags=evidence_tags,
        safety_notes=[
            "Draft only. Teacher approval required.",
            "Uses skill language, not deficit labels.",
        ],
    )
    _validate_safe_text(record.title, record.body)
    return record


def _record_from_payload(payload: dict, kind: str) -> HelpArtifactRecord | PortfolioEntryRecord:
    draft = payload.get("draft") if isinstance(payload.get("draft"), dict) else payload
    if kind == "help_artifact":
        return HelpArtifactRecord.from_dict(draft)
    return PortfolioEntryRecord.from_dict(draft)


def _apply_help_edits(record: HelpArtifactRecord, teacher_edits: dict[str, Any] | None) -> HelpArtifactRecord:
    edits = teacher_edits or {}
    data = record.as_dict()
    for field_name in ("title", "instructions", "student_prompt"):
        if isinstance(edits.get(field_name), str) and edits[field_name].strip():
            data[field_name] = _compact(edits[field_name], 2000)
    if isinstance(edits.get("teacher_notes"), list):
        data["teacher_notes"] = [_compact(item, 400) for item in edits["teacher_notes"] if str(item).strip()]
    data["status"] = "approved"
    _validate_safe_text(data["title"], data["instructions"], data["student_prompt"], *data.get("teacher_notes", []))
    return HelpArtifactRecord.from_dict(data)


def _apply_portfolio_edits(record: PortfolioEntryRecord, teacher_edits: dict[str, Any] | None) -> PortfolioEntryRecord:
    edits = teacher_edits or {}
    data = record.as_dict()
    for field_name in ("title", "body"):
        if isinstance(edits.get(field_name), str) and edits[field_name].strip():
            data[field_name] = _compact(edits[field_name], 3000)
    data["status"] = "approved"
    _validate_safe_text(data["title"], data["body"])
    return PortfolioEntryRecord.from_dict(data)


def approve_help_artifact(record_or_payload: HelpArtifactRecord | dict, teacher_edits: dict[str, Any] | None = None) -> HelpArtifactRecord:
    record = record_or_payload if isinstance(record_or_payload, HelpArtifactRecord) else _record_from_payload(record_or_payload, "help_artifact")
    approved = _apply_help_edits(record, teacher_edits)
    return approved


def approve_portfolio_entry(record_or_payload: PortfolioEntryRecord | dict, teacher_edits: dict[str, Any] | None = None) -> PortfolioEntryRecord:
    record = record_or_payload if isinstance(record_or_payload, PortfolioEntryRecord) else _record_from_payload(record_or_payload, "portfolio_entry")
    approved = _apply_portfolio_edits(record, teacher_edits)
    return approved


def content_hash(record: HelpArtifactRecord | PortfolioEntryRecord | dict) -> str:
    data = record if isinstance(record, dict) else record.as_dict()
    return _hash_payload(json.dumps(data, sort_keys=True, ensure_ascii=True))
