"""
Ops Bot-Spec — the compiled per-school configuration for the Slack Daily
Operations Assistant (v2).

Spec: dev/specs/SPEC_LV_SLACK_OPS_V2_WORKFLOW_PACKS_2026-07-27.md §3.2.

Design decisions (operator-ruled 2026-07-27):
  - ONE YAML file per school: selected packs + interview answers
    (channels/times/period aliases/claim rights/review-required) +
    learned rules + corpus results. The admin NEVER hand-edits it — it is
    produced by setup and the teach loop (generated header says so) and
    reviewed read-only in the desktop app.
  - Location: lv_home()/ops/bot_spec.yaml; LV_OPS_BOT_SPEC_PATH override
    for hermetic tests. The app never writes into LV_ROOT — shipped packs
    at config/ops_packs/ stay read-only data.
  - Loading: load_compiled_spec() → immutable CompiledBotSpec consumed by
    classifier + daily engine + bot through the ops_packs current-compile
    seam. Reload semantics (ruled): ATOMIC IN-PROCESS SWAP — setup/teach
    routes rebuild the CompiledBotSpec and swap one reference. No file
    watchers, no hot partial reload, no app restart.
  - Fail-closed: malformed/unreadable/oversized bot-spec → fall back to
    the v1-parity default compile with a `fallback` reason (surfaced as a
    health WARN on the status/bot-spec routes). Never crash the bot,
    never half-apply.
  - Backward compatibility (spec §3.3 — Claudia is LIVE): no bot-spec
    file + env configured ⇒ exact v1 behavior. The go-live gate applies
    ONLY when a bot-spec exists; creating one never silently stops a
    running env-configured bot (the PUT route swaps the compile but does
    not touch the transport).
  - Secrets stay in env exactly as v1 (LV_SLACK_*). The bot-spec never
    contains tokens — write_bot_spec() refuses content carrying
    xoxb-/xapp- shaped strings, and a test asserts it.
  - Atomic writes (mkstemp + os.replace, same-directory temp), a
    schema_version field from day one.
  - Learned rules (spec §4): conservative exact-keyphrase, normalized
    (lowercase, collapsed whitespace); compiled patterns derive from the
    keyphrase at compile time (single source of truth). Only
    status=approved rules compile in; candidates NEVER affect live
    classification. Lifecycle: candidate → corpus re-test → approved |
    rejected | expired.
  - YAML loading uses the shared guarded loader (size cap + alias-bomb
    refusal — the one-button-update lane already ate a 419-byte alias
    bomb; see ops_packs.load_yaml_guarded).
"""

from __future__ import annotations

import logging
import os
import re
import tempfile
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import yaml

from src.education import ops_packs
from src.education.ops_packs import (
    CompiledRuleSet,
    PackLoadError,
    load_yaml_guarded,
)

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 1
MAX_BOT_SPEC_BYTES = ops_packs.MAX_PACK_BYTES

GENERATED_HEADER = (
    "# GENERATED by Lingua Viva — do not hand-edit.\n"
    "# This file is produced by the Bot Setup panel and the teach loop.\n"
    "# Review it read-only in the desktop app; changes made here by hand\n"
    "# may be overwritten at any time.\n"
)

# Token shapes that must never appear in a bot-spec (secrets live in env).
_SECRET_RE = re.compile(r"\b(?:xoxb-|xapp-|xoxp-|xoxa-)", re.IGNORECASE)

_HHMM_RE = re.compile(r"^\d{1,2}:\d{2}$")

RULE_STATUSES = ("candidate", "approved", "rejected", "expired")

DEFAULT_BRIEFING_HHMM = "07:30"
DEFAULT_EOD_HHMM = "16:30"


def bot_spec_path() -> Path:
    override = os.environ.get("LV_OPS_BOT_SPEC_PATH")
    if override:
        return Path(override).expanduser()
    from src.lingua_viva.config import lv_home
    return lv_home() / "ops" / "bot_spec.yaml"


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def normalize_keyphrase(phrase: str) -> str:
    """Conservative normalization (spec §4): lowercase, collapsed
    whitespace. The distinctive phrase the admin confirms — never the
    whole sentence, never auto-generalized further."""
    return re.sub(r"\s+", " ", (phrase or "")).strip().lower()


def keyphrase_pattern(phrase: str) -> str:
    """Exact-keyphrase regex derived from the normalized phrase.
    Word-bounded, escaped — matching is literal, not generalized.
    `\\b` only anchors against word characters, so a phrase ending in
    punctuation (e.g. "room 3 (annex)") gets no trailing anchor — the
    punctuation itself already bounds the match."""
    normalized = normalize_keyphrase(phrase)
    if not normalized:
        return ""
    escaped = re.escape(normalized).replace(r"\ ", r"\s+")
    word_re = re.compile(r"[\w]")
    prefix = r"\b" if word_re.match(normalized[0]) else ""
    suffix = r"\b" if word_re.match(normalized[-1]) else ""
    return f"{prefix}{escaped}{suffix}"


@dataclass(frozen=True)
class CompiledBotSpec:
    """Immutable compile of one school's bot-spec (spec §3.2). Swapped as
    one reference — never mutated in place."""

    exists: bool
    live: bool
    schema_version: int
    enabled_pack_ids: tuple
    briefing_hhmm: str
    eod_hhmm: str
    period_aliases: tuple          # raw pattern strings (settings)
    claim_rights: str
    review_required: tuple
    learned_rules: tuple           # raw rule dicts, all statuses
    corpus_sentences: tuple        # admin-added sample dicts
    corpus_last_run: Optional[dict]
    rule_set: CompiledRuleSet
    fallback: Optional[str] = None  # set ⇒ parity fallback, health WARN
    raw: dict = field(default_factory=dict)

    def approved_rules(self) -> tuple:
        return tuple(
            r for r in self.learned_rules if r.get("status") == "approved"
        )

    def candidate_rules(self) -> tuple:
        return tuple(
            r for r in self.learned_rules if r.get("status") == "candidate"
        )


def _parity_spec(*, exists: bool = False, fallback: Optional[str] = None,
                 raw: Optional[dict] = None, live: bool = False) -> CompiledBotSpec:
    rule_set = ops_packs.default_rule_set()
    return CompiledBotSpec(
        exists=exists,
        live=live,
        schema_version=SCHEMA_VERSION,
        enabled_pack_ids=rule_set.enabled_pack_ids,
        briefing_hhmm=DEFAULT_BRIEFING_HHMM,
        eod_hhmm=DEFAULT_EOD_HHMM,
        period_aliases=(),
        claim_rights="roster",
        review_required=(),
        learned_rules=(),
        corpus_sentences=(),
        corpus_last_run=None,
        rule_set=rule_set,
        fallback=fallback,
        raw=dict(raw or {}),
    )


def _valid_hhmm(value, default: str) -> str:
    text = str(value or "").strip()
    if _HHMM_RE.match(text):
        hour, minute = (int(part) for part in text.split(":"))
        if 0 <= hour <= 23 and 0 <= minute <= 59:
            return text
    return default


def _compile_from_data(data: dict) -> CompiledBotSpec:
    """Strict compile — raises PackLoadError on structural surprises so
    load_compiled_spec can fail closed to parity."""
    if not isinstance(data, dict):
        raise PackLoadError("bot-spec must be a YAML mapping")
    schema_version = int(data.get("schema_version") or 0)
    if schema_version != SCHEMA_VERSION:
        raise PackLoadError(f"unsupported bot-spec schema_version {schema_version!r}")

    packs_block = data.get("packs")
    if not isinstance(packs_block, dict) or not isinstance(
        packs_block.get("enabled"), list
    ):
        raise PackLoadError("bot-spec packs.enabled must be a list")
    enabled = [str(p) for p in packs_block["enabled"]]
    known = set(ops_packs.load_packs())
    unknown = [p for p in enabled if p not in known]
    if unknown:
        raise PackLoadError(f"bot-spec enables unknown packs: {unknown}")

    settings = data.get("settings")
    settings = settings if isinstance(settings, dict) else {}
    briefing = _valid_hhmm(settings.get("briefing_hhmm"), DEFAULT_BRIEFING_HHMM)
    eod = _valid_hhmm(settings.get("eod_hhmm"), DEFAULT_EOD_HHMM)
    aliases = tuple(
        str(a) for a in settings.get("period_aliases") or [] if str(a).strip()
    )
    claim_rights = str(settings.get("claim_rights") or "roster")
    review_required = tuple(
        str(c) for c in settings.get("review_required") or [] if str(c).strip()
    )

    learned = []
    for raw_rule in data.get("learned_rules") or []:
        if not isinstance(raw_rule, dict):
            raise PackLoadError("bot-spec learned_rules entries must be mappings")
        status = str(raw_rule.get("status") or "")
        if status not in RULE_STATUSES:
            raise PackLoadError(f"bot-spec learned rule has bad status {status!r}")
        learned.append(dict(raw_rule))

    corpus = data.get("corpus")
    corpus = corpus if isinstance(corpus, dict) else {}
    sentences = tuple(
        dict(s) for s in corpus.get("admin_sentences") or [] if isinstance(s, dict)
    )
    last_run = corpus.get("last_run")
    last_run = dict(last_run) if isinstance(last_run, dict) else None

    # Only APPROVED rules compile in (spec §4: candidates never affect
    # live classification). Patterns derive from the keyphrase here.
    compiled_rules = []
    for rule in learned:
        if rule.get("status") != "approved":
            continue
        pattern = keyphrase_pattern(str(rule.get("keyphrase") or ""))
        if pattern:
            compiled_rules.append(
                {"category": str(rule.get("category") or ""), "pattern": pattern}
            )

    rule_set = ops_packs.compile_rule_set(
        enabled,
        review_required=set(review_required),
        learned_rules=compiled_rules,
        period_alias_patterns=list(aliases),
    )

    return CompiledBotSpec(
        exists=True,
        live=bool(data.get("live", False)),
        schema_version=schema_version,
        enabled_pack_ids=tuple(enabled),
        briefing_hhmm=briefing,
        eod_hhmm=eod,
        period_aliases=aliases,
        claim_rights=claim_rights,
        review_required=review_required,
        learned_rules=tuple(learned),
        corpus_sentences=sentences,
        corpus_last_run=last_run,
        rule_set=rule_set,
        fallback=None,
        raw=dict(data),
    )


def load_compiled_spec(path: Optional[Path] = None) -> CompiledBotSpec:
    """Load + compile the bot-spec. No file ⇒ v1-parity (exists=False).
    Malformed/oversized/unreadable ⇒ v1-parity WITH a fallback reason
    (fail closed — never crash the bot, never half-apply)."""
    spec_path = Path(path) if path else bot_spec_path()
    try:
        raw = spec_path.read_bytes()
    except FileNotFoundError:
        return _parity_spec(exists=False)
    except OSError as exc:
        return _parity_spec(
            exists=True, fallback=f"bot-spec unreadable ({type(exc).__name__})"
        )
    try:
        data = load_yaml_guarded(raw, max_bytes=MAX_BOT_SPEC_BYTES)
        return _compile_from_data(data)
    except PackLoadError as exc:
        logger.warning("[ops-bot-spec] fail-closed to v1 parity: %s", exc)
        return _parity_spec(exists=True, fallback=str(exc))


def write_bot_spec(data: dict, path: Optional[Path] = None) -> Path:
    """Atomically write the bot-spec YAML with the generated header.
    Refuses content carrying Slack-token shapes — secrets live in env
    only (spec §3.2)."""
    payload = dict(data)
    payload["schema_version"] = SCHEMA_VERSION
    payload.setdefault("updated_at", utc_now_iso())
    serialized = yaml.safe_dump(payload, sort_keys=True, allow_unicode=True)
    if _SECRET_RE.search(serialized):
        raise ValueError("bot-spec must never contain Slack tokens (secrets stay in env)")
    content = GENERATED_HEADER + serialized
    target = Path(path) if path else bot_spec_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=".bot-spec-", suffix=".tmp", dir=str(target.parent)
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp_name, target)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise
    return target


def default_bot_spec_data(enabled_pack_ids: Optional[list] = None) -> dict:
    """A fresh bot-spec document (setup panel starting point): launch
    packs pre-checked, v1 defaults, not live until the corpus gate."""
    if enabled_pack_ids is None:
        packs = ops_packs.load_packs()
        enabled_pack_ids = [p.id for p in packs.values() if p.enabled_by_default]
    return {
        "schema_version": SCHEMA_VERSION,
        "live": False,
        "packs": {"enabled": sorted(enabled_pack_ids)},
        "settings": {
            "briefing_hhmm": DEFAULT_BRIEFING_HHMM,
            "eod_hhmm": DEFAULT_EOD_HHMM,
            "period_aliases": [],
            "claim_rights": "roster",
            "review_required": [],
        },
        "learned_rules": [],
        "corpus": {"admin_sentences": [], "last_run": None},
    }


def new_candidate_rule(
    *, category: str, keyphrase: str, source_record_id: str, admin: str = "admin"
) -> dict:
    """Candidate rule with provenance (spec §4). Not compiled until
    approved by the corpus-gated promote ceremony."""
    return {
        "id": f"lr-{uuid.uuid4().hex[:12]}",
        "category": category,
        "keyphrase": normalize_keyphrase(keyphrase),
        "status": "candidate",
        "provenance": {
            "source_record_id": source_record_id,
            "admin_action": admin,
            "created_at": utc_now_iso(),
        },
    }


# ---------------------------------------------------------------------------
# Current-spec seam (spec §3.2: atomic in-process swap; no file watchers)
# ---------------------------------------------------------------------------

_current_spec: Optional[CompiledBotSpec] = None


def current_spec() -> CompiledBotSpec:
    """The installed compile; loads (and installs) from disk on first use."""
    global _current_spec
    if _current_spec is None:
        install_compiled_spec(load_compiled_spec())
    return _current_spec


def install_compiled_spec(spec: Optional[CompiledBotSpec]) -> None:
    """Atomic swap: one reference here plus the rule-set reference the
    classifier/daily/bot read through. None resets to parity."""
    global _current_spec
    _current_spec = spec
    ops_packs.install_rule_set(spec.rule_set if spec is not None else None)


def refresh_from_disk(path: Optional[Path] = None) -> CompiledBotSpec:
    """Reload + swap (called by setup/teach routes after a write, and by
    web startup). Never stops a running bot — transport lifecycle is
    owned by web startup/shutdown, not by the compile."""
    spec = load_compiled_spec(path)
    install_compiled_spec(spec)
    return spec
