#!/usr/bin/env python3
"""Build the SYNTHETIC detection corpus — Phase 0B.4 of
SPEC_LV_UNIFIED_REAL_DATA_FIX_2026-08-19.

Generates ``tests/fixtures/docpipe/synthetic-corpus/`` — a committed,
synthetic-name mirror of the four structural shapes in the REAL corpus
(which lives outside the repo and is never committed). CI scores the
detection pipeline against this mirror via the corpus tests; the real
numbers come from running the same scorer locally against the real files.

The generator is deterministic (fixed names, no randomness) so the
committed fixtures can be regenerated byte-comparably at any time:

    python3 scripts/build_synthetic_corpus.py

Shapes mirrored (structure faithful, names synthetic):
1. grade_sheet_class_list — row 1: class names heading column PAIRS
   (Last|First), row 2: teacher names, rows 3+: Last/First per column
   pair, plus "1/2 groups ..." scheduling-note rows that are NOT students.
2. single_sheet_support — literal "Student"/"class" headers, abbreviated
   names ("First L-W" style), a target class "V".
3. per_class_sheet_support — class code in row 1, a staff first-name
   block ABOVE an "Accommodations ... / Medical needs ..." header row,
   students below it. Staff must never be detected as students.
4. curriculum_mapping + cycle_calendar — ZERO students; packed with the
   non-English capitalized bigrams that produced the false positives.
"""
from __future__ import annotations

import json
from pathlib import Path

CORPUS_DIR = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "docpipe" / "synthetic-corpus"


# ---------------------------------------------------------------------------
# Synthetic people (never real names)
# ---------------------------------------------------------------------------

# Class list: two classes per grade sheet, Last/First column pairs.
CLASS_LIST = {
    "Grade 3": {
        "Verdi": {
            "teacher": "Ilaria Moretti",
            "students": [  # (last, first) as they appear in the columns
                ("Bianchi", "Marco"),
                ("Rossi", "Nora"),
                ("Conti", "Sara"),
                ("Ferri", "Luca"),
                ("Greco", "Elisa"),
                ("Marini", "Tommaso"),
            ],
        },
        "Arancioni": {
            "teacher": "Davide Colombo",
            "students": [
                ("Riva", "Giulia"),
                ("Serra", "Pietro"),
                ("Villa", "Anna (Annie)"),
                ("Fontana", "Leo"),
                ("Gatti", "Camilla"),
            ],
        },
    },
    "Grade 6": {
        "Blu": {
            "teacher": "Chiara De Luca",
            "students": [
                ("Barbieri", "Matteo"),
                ("Caruso", "Sofia"),
                ("Longo", "Emma"),
                ("Marchetti", "Diego"),
            ],
        },
        "Gialli": {
            "teacher": "Stefano Ricci",
            "students": [
                ("Monti", "Alice"),
                ("Neri", "Filippo"),
                ("Pellegrini", "Viola"),
                ("Sanna", "Oscar"),
            ],
        },
    },
}

# Scheduling-note rows (NOT students) — placed inside the roster columns.
CLASS_LIST_NOTE_ROWS = [
    "1/2 groups alternate Fridays",
    "1/2 groups swap after break",
]

# Single-sheet support: abbreviated names, three in the target class "V".
SUPPORT_3V = [
    # (abbreviated name as written, class)
    ("Marco B-R", "V"),
    ("Nora R-S", "V"),
    ("Elisa G-M", "V"),
    ("Giulia R-V", "A"),
    ("Matteo B-C", "A"),
    ("Viola P-S", "A"),
]

# Per-class-sheet support (K-5 shape): class code row 1, staff first-name
# block, then the accommodations header row, then students.
SUPPORT_K5 = {
    "KV": {
        "staff": ["Ilaria", "Davide", "Paola"],
        "students": ["Marco Bianchi", "Nora Rossi", "Sara Conti"],
    },
    "1A": {
        "staff": ["Chiara", "Stefano"],
        "students": ["Giulia Riva", "Pietro Serra", "Leo Fontana", "Camilla Gatti"],
    },
}

# Zero-student files: the capitalized non-English bigrams that fooled the
# detector into 144 + 86 false positives on the real files.
CURRICULUM_ROWS = [
    ("Unità Uno", "Le Stagioni", "Autunno Inverno"),
    ("Unità Due", "La Famiglia", "Nonna Nonno"),
    ("Unità Tre", "Il Corpo Umano", "Scienze Naturali"),
    ("Unità Quattro", "Primavera Estate", "Feste Tradizioni"),
    ("Mappatura UOI", "Chi Siamo", "Come Funziona"),
    ("Valutazione Formativa", "Lettura Guidata", "Scrittura Creativa"),
]

CALENDAR_ROWS = [
    ("Day 1", "Music Room", "Lunedì Settembre"),
    ("Day 2", "Art Studio", "Martedì Ottobre"),
    ("Day 3", "Assembly Hall", "Mercoledì Novembre"),
    ("Day 4", "Sports Field", "Giovedì Dicembre"),
    ("Day 5", "Library Corner", "Venerdì Gennaio"),
    ("Day 6", "Science Lab", "Winter Break"),
]


def _build_class_list(path: Path) -> list[str]:
    import openpyxl

    wb = openpyxl.Workbook()
    wb.remove(wb.active)
    expected: list[str] = []
    for grade, classes in CLASS_LIST.items():
        ws = wb.create_sheet(title=grade)
        col = 1
        for class_name, info in classes.items():
            ws.cell(row=1, column=col, value=class_name)
            ws.cell(row=2, column=col, value=info["teacher"])
            row = 3
            for last, first in info["students"]:
                ws.cell(row=row, column=col, value=last)
                ws.cell(row=row, column=col + 1, value=first)
                expected.append(f"{first} {last}")
                row += 1
            # scheduling-note rows live INSIDE the roster columns and must
            # never be detected as students
            for note in CLASS_LIST_NOTE_ROWS:
                ws.cell(row=row, column=col, value=note)
                row += 1
            col += 2
    wb.save(path)
    return expected


def _build_support_3v(path: Path) -> list[str]:
    import openpyxl

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    ws.append(["Student", "class", "Support notes", "Review date"])
    for name, class_code in SUPPORT_3V:
        ws.append([name, class_code, "Reading support", "2026-09-01"])
    wb.save(path)
    return [name for name, _ in SUPPORT_3V]


def _build_support_k5(path: Path) -> list[str]:
    import openpyxl

    wb = openpyxl.Workbook()
    wb.remove(wb.active)
    expected: list[str] = []
    for class_code, info in SUPPORT_K5.items():
        ws = wb.create_sheet(title=class_code)
        ws.cell(row=1, column=1, value=class_code)
        row = 2
        for staff_name in info["staff"]:
            ws.cell(row=row, column=1, value=staff_name)
            ws.cell(row=row, column=2, value="support staff")
            row += 1
        ws.cell(row=row, column=1, value="Student")
        ws.cell(row=row, column=2, value="Accommodations in the classroom")
        ws.cell(row=row, column=3, value="Medical needs / allergies")
        row += 1
        for student in info["students"]:
            ws.cell(row=row, column=1, value=student)
            ws.cell(row=row, column=2, value="Extra time")
            ws.cell(row=row, column=3, value="None")
            expected.append(student)
            row += 1
    wb.save(path)
    return expected


def _build_zero_student(path: Path, rows: list[tuple[str, ...]], title: str) -> None:
    import openpyxl

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = title
    for row in rows:
        ws.append(list(row))
    wb.save(path)


def main() -> int:
    CORPUS_DIR.mkdir(parents=True, exist_ok=True)
    files = []

    expected = _build_class_list(CORPUS_DIR / "synthetic_class_list.xlsx")
    files.append({
        "file": "synthetic_class_list.xlsx",
        "shape": "grade_sheet_class_list",
        "expected_students": expected,
        "sealed": False,
        "note": "row1 class pairs, row2 teachers, Last/First columns, note rows are not students",
    })

    expected = _build_support_3v(CORPUS_DIR / "synthetic_support_3v.xlsx")
    files.append({
        "file": "synthetic_support_3v.xlsx",
        "shape": "single_sheet_support",
        "expected_students": expected,
        "sealed": False,
        "target_class": "V",
        "note": "literal Student/class headers, abbreviated names, 3 of 6 in class V",
    })

    expected = _build_support_k5(CORPUS_DIR / "synthetic_support_k5.xlsx")
    files.append({
        "file": "synthetic_support_k5.xlsx",
        "shape": "per_class_sheet_support",
        "expected_students": expected,
        "sealed": False,
        "note": "class code row 1, staff first-name block, accommodations header, students below",
    })

    _build_zero_student(CORPUS_DIR / "synthetic_curriculum.xlsx", CURRICULUM_ROWS, "Mappatura")
    files.append({
        "file": "synthetic_curriculum.xlsx",
        "shape": "curriculum_mapping",
        "expected_students": [],
        "sealed": False,
        "note": "zero students — Italian capitalized bigrams must not be detected",
    })

    _build_zero_student(CORPUS_DIR / "synthetic_calendar.xlsx", CALENDAR_ROWS, "Cycle")
    files.append({
        "file": "synthetic_calendar.xlsx",
        "shape": "cycle_calendar",
        "expected_students": [],
        "sealed": False,
        "note": "zero students — Day-cycle grid, room names, month bigrams",
    })

    labels_path = CORPUS_DIR / "labels.json"
    labels_path.write_text(
        json.dumps({"corpus": "synthetic", "files": files}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    total = sum(len(f["expected_students"]) for f in files)
    print(f"synthetic corpus written to {CORPUS_DIR} — {len(files)} files, {total} expected students")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
