#!/usr/bin/env python3
"""UI bundle contract checker (MC-lessons §3, 2026-07-19).

Cloned from Mission Canvas's own proven `scripts/check_wizard_contract.py`
shape — a hash-lock over the teacher-facing UI surface, so it cannot drift
silently. LV's contract is simpler than MC's wizard contract (no journey
anchors / live-route smoke check needed yet — the teacher UI has no
onboarding wizard of its own): just a version-pinned SHA-256 lock over the
protected files.

  check (default)   Verify contract files exist and content hashes match
                    the lock. Exit 1 on any violation. Runs in well under
                    a second — used by `lv preflight`.
  --bump            Deliberately change the UI: increments `version` in
                    contracts/UI_CONTRACT.yaml and re-locks all hashes.

Spec: dev/specs/SPEC_APP_IMPROVEMENT_MC_LESSONS_2026-07-19.md §3.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CONTRACT = REPO / "contracts" / "UI_CONTRACT.yaml"
LOCK = REPO / "contracts" / "UI_CONTRACT.lock"


def load_contract() -> dict:
    text = CONTRACT.read_text(encoding="utf-8")
    data = yaml.safe_load(text) or {}
    if "version" not in data or "files" not in data:
        fail(f"{CONTRACT}: missing 'version' or 'files'")
    return data


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def fail(msg: str) -> None:
    print(f"[ui-contract] FAIL: {msg}")
    print("[ui-contract] The teacher UI bundle is contract-protected.")
    print("[ui-contract] If this change is deliberate, run:")
    print("[ui-contract]   python3 scripts/check_ui_contract.py --bump")
    sys.exit(1)


def check() -> None:
    c = load_contract()

    for rel in c["files"]:
        p = REPO / rel
        if not p.is_file():
            fail(f"protected file missing: {rel}")
        if p.stat().st_size < 500:
            fail(f"protected file suspiciously small (<500 bytes): {rel}")

    if not LOCK.is_file():
        fail("lock file missing: contracts/UI_CONTRACT.lock (run --bump to create)")
    lock = json.loads(LOCK.read_text(encoding="utf-8"))
    if lock.get("version") != c["version"]:
        fail(
            f"contract version ({c['version']}) != lock version "
            f"({lock.get('version')}) — run --bump to re-lock"
        )
    for rel in c["files"]:
        actual = sha256(REPO / rel)
        expected = lock.get("hashes", {}).get(rel)
        if expected is None:
            fail(f"file not in lock: {rel} — run --bump to re-lock")
        if actual != expected:
            fail(
                f"protected file changed without version bump: {rel}\n"
                f"[ui-contract]   locked  {expected[:16]}…\n"
                f"[ui-contract]   actual  {actual[:16]}…"
            )

    print(f"[ui-contract] OK — contract v{c['version']}, {len(c['files'])} files locked")


def bump() -> None:
    c = load_contract()
    new_version = c["version"] + 1
    text = CONTRACT.read_text(encoding="utf-8")
    import re

    text = re.sub(r"^version:\s*\d+\s*$", f"version: {new_version}", text, count=1, flags=re.M)
    CONTRACT.write_text(text, encoding="utf-8")
    lock = {
        "comment": "AUTO-GENERATED by check_ui_contract.py --bump. Never edit by hand.",
        "version": new_version,
        "hashes": {rel: sha256(REPO / rel) for rel in c["files"]},
    }
    LOCK.write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")
    print(f"[ui-contract] bumped to v{new_version}, {len(c['files'])} files re-locked")
    print("[ui-contract] add a bump-log line to contracts/UI_CONTRACT.yaml explaining why,")
    print("[ui-contract] then commit contracts/UI_CONTRACT.yaml and .lock together with your change")


if __name__ == "__main__":
    if sys.argv[1:2] == ["--bump"]:
        bump()
    else:
        check()
