"""Build the C8 durability fixture: a lens store as the shipped release writes it.

C8 (dev/PATH_TO_UX_READINESS_2026-09-04.md, dev/PLAN_PC23_LV_UX_LANE_2026-09-04.md #3):
install-over-install keeps every lens. The half of that promise this repo can
test without an installer is "the store a teacher already has on disk survives
the NEXT release's code opening it" — so the fixture is a frozen SQL dump of a
store written by the shipped code, and tests/test_c8_install_over_install.py
opens it with the current code and counts.

Provenance of tests/fixtures/c8/student_lenses_v0.2.84.sql:
  generated 2026-09-04 on PC-23 at f22e7a6 with THIS script. At that commit
  `git diff 71b069d -- src/education/student_lens.py` carries no CREATE/ALTER
  change, i.e. the schema is byte-for-byte the one desktop-v0.2.84 ships.
  Names are the demo-data/classe-3B.csv fixtures (fictional). No real child.

Regenerate only when a release is cut whose schema you want to freeze as the
"previous" one — and then ADD a new file, never overwrite this one: the point
is that old stores keep opening.

Usage:  python scripts/make_c8_fixture.py [out.sql]
"""
from __future__ import annotations

import sqlite3
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from src.education.student_lens import Observation, StudentLensStore  # noqa: E402

ROSTER = [
    ("s-luca-rossi", "Lucà Rossi"),
    ("s-noemi-villa", "Noëmi Villa"),
    ("s-chang-abigail", "Chang Abigail"),
    ("s-chang-marco", "Chang Marco"),
    ("s-bianchi-sofia", "Bianchi Sofia"),
    ("s-giuseppe-esposito", "Giuseppe Esposito"),
]
TEACHER = "teacher-fixture"


def build(out: Path) -> None:
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as td:  # Windows keeps the db handle briefly
        db = Path(td) / "student_lenses.db"
        store = StudentLensStore(db_path=db)
        for sid, name in ROSTER:
            store.create_lens(
                student_id=sid, display_name=name, campus="classe-3B",
                grade_level="3", home_languages=["it"],
            )
            store.add_to_roster(TEACHER, sid, source="fixture")
        # Every kind of row a real store carries after a week of use.
        store.set_initial_cefr("s-luca-rossi", "A2", TEACHER)
        store.append_observation(Observation(
            student_id="s-noemi-villa", teacher_id=TEACHER, template_type="cefr",
            raw_transcript="Noëmi read the whole page aloud with good intonation.",
            cefr_dimension="speaking", cefr_level_observed="A2+",
        ))
        store.append_observation(Observation(
            student_id="s-chang-abigail", teacher_id=TEACHER, template_type="general",
            raw_transcript="Finished early again; could benefit from extension activities.",
        ))
        store.add_support_entry(
            "s-chang-abigail", "learning_and_cognition", "strengths",
            "Works independently and finishes early", TEACHER,
        )
        store.add_support_entry(
            "s-bianchi-sofia", "learning_and_cognition", "strategies_worked",
            "Sentence starters on the desk", TEACHER,
        )
        store.record_rti_decision("s-chang-marco", "defer", "Reading fluency check in two weeks")
        store.append_evidence({
            "student_id": "s-giuseppe-esposito", "teacher_id": TEACHER,
            "kind": "teacher_feedback", "target_type": "support_category",
            "target_id": "learning_and_cognition",
            "summary": "Built the model bridge with the group",
        })
        store.close()

        conn = sqlite3.connect(db)
        dump = "\n".join(conn.iterdump())
        conn.close()

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "-- C8 fixture: student lens store as written by the shipped release.\n"
        "-- Generated by scripts/make_c8_fixture.py (see its docstring for provenance).\n"
        "-- Fictional students from demo-data/classe-3B.csv. Never edit by hand.\n"
        + dump + "\n",
        encoding="utf-8", newline="\n",
    )
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "tests" / "fixtures" / "c8" / "student_lenses_v0.2.84.sql"
    build(target)
